### ISSUE TITLE
Redundancy of `Data.Some`

### ISSUE THREAD

**Issue by buzden** [JankaGramofonomanka/idris-dtypes#2]
Correct me it I'm wrong, but your `Data.Some` is just a copy of `Exists` type from `Data.DPair` module from `base`

**Comment by JankaGramofonomanka** [comment]
Looks like you are correct. However, I am not convinced this means I should get rid of it.
It seems to me there is a value in the different naming.

**Comment by buzden** [comment]
Oh, sure, it's up to you
